name: CI Pipeline

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git checkout HEAD^

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v4

      - name: Cache Maven Packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # TODO: infrastructure for integration tests with docker-compose

#      - name: Run Tests
#        run: mvn -B test

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-v2-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: |
            cd agent-fe
            npm install
      
      - name: Build
        run: |
            cd agent-fe
            npm run build


